return function(colour_palette)
    local colors = colour_palette.base_30
    return {
        DevIconC = { fg = colors.blue },
        DevIconCss = { fg = colors.blue },
        DevIconDeb = { fg = colors.cyan },
        DevIconDefault = { fg = colors.red },
        DevIconDockerfile = { fg = colors.cyan },
        DevIconGitAttributes = { fg = "#E94E31" },
        DevIconGitCommit = { fg = "#E94E31" },
        DevIconGitConfig = { fg = "#E94E31" },
        DevIconGitIgnore = { fg = "#E94E31" },
        DevIconGitLogo = { fg = "#E94E31" },
        DevIconGitModules = { fg = "#E94E31" },
        DevIconHtm = { fg = "#DF4A17" },
        DevIconHtml = { fg = "#DF4A17" },
        DevIconJS = { fg = "#E9D44D" },
        DevIconJpeg = { fg = colors.dark_purple },
        DevIconJpg = { fg = colors.dark_purple },
        DevIconJs = { fg = colors.sun },
        DevIconKt = { fg = colors.orange },
        DevIconLock = { fg = colors.red },
        DevIconLua = { fg = colors.blue },
        DevIconMarkdown = { fg = "#822D06" },
        DevIconMd = { fg = "#822D06" },
        DevIconMp3 = { fg = colors.white },
        DevIconMp4 = { fg = colors.white },
        DevIconOut = { fg = colors.white },
        DevIconPng = { fg = colors.dark_purple },
        DevIconPy = { fg = colors.cyan },
        DevIconRb = { fg = colors.pink },
        DevIconRpm = { fg = colors.orange },
        DevIconToml = { fg = colors.blue },
        DevIconTs = { fg = colors.teal },
        DevIconTtf = { fg = colors.white },
        DevIconVue = { fg = colors.vibrant_green },
        DevIconWoff = { fg = colors.white },
        DevIconWoff2 = { fg = colors.white },
        DevIconXz = { fg = colors.sun },
        DevIconZip = { fg = colors.sun },
    }
end
