return function(colour_palette)
    return {
        NavicIconsFile = { link = "TSURI" },
        NavicIconsModule = { link = "TSNamespace" },
        NavicIconsNamespace = { link = "TSNamespace" },
        NavicIconsPackage = { link = "TSNamespace" },
        NavicIconsClass = { link = "TSType" },
        NavicIconsMethod = { link = "TSMethod" },
        NavicIconsProperty = { link = "TSMethod" },
        NavicIconsField = { link = "TSField" },
        NavicIconsConstructor = { link = "TSConstructor" },
        NavicIconsEnum = { link = "TSType" },
        NavicIconsInterface = { link = "TSType" },
        NavicIconsFunction = { link = "TSFunction" },
        NavicIconsVariable = { link = "TSConstant" },
        NavicIconsConstant = { link = "TSConstant" },
        NavicIconsString = { link = "TSString" },
        NavicIconsNumber = { link = "TSNumber" },
        NavicIconsBoolean = { link = "TSBoolean" },
        NavicIconsArray = { link = "TSConstant" },
        NavicIconsObject = { link = "TSType" },
        NavicIconsKey = { link = "TSType" },
        NavicIconsNull = { link = "TSType" },
        NavicIconsEnumMember = { link = "TSField" },
        NavicIconsStruct = { link = "TSType" },
        NavicIconsEvent = { link = "TSType" },
        NavicIconsOperator = { link = "TSOperator" },
        NavicIconsTypeParameter = { link = "TSParameter" },
    }
end
